<?php
$users = [
  'damai' => [
    'nickname' => 'damai',
    'pass' => 'a',
    'name' => 'Damai Miracle Tampubolon',
    'birtdate' => '21 February 1997',
    'email' => 'damaimiracle@gmail.com',
    'phone' => '6281336698883',
    'address' => 'Jalan Minas 7, Blok G7 no. 27, Jatiwaringin, Bekasi',
    'joindate' => 'September 2024',
    'position' => 'Head Coach',
    'schedule' => 'Monday & Saturday',
  ],
  'kenda' => [
    'nickname' => 'kenda',
    'pass' => 'a',
    'name' => 'M Keinanda Alam',
    'birtdate' => '13 September 1999',
    'email' => 'akeinanda@gmail.com',
    'phone' => '6285776675400',
    'address' => 'Apartemen Menara Kebon Jeruk. Jl.Arjuna Utara - Jakarta Barat',
    'joindate' => 'September 2024',
    'position' => 'U10 Coach',
    'schedule' => 'Saturday',
  ],
  'rafly' => [
    'nickname' => 'rafly',
    'pass' => 'a',
    'name' => 'Muhammad Rafly Alfariz',
    'birtdate' => '03 September 2002',
    'email' => 'raflyalfariz@gmail.com',
    'phone' => '6282120242003',
    'address' => 'Taman Adhiloka Blok K 16, Tangerang, Banten',
    'joindate' => 'August 2025',
    'position' => 'U12 Borussia Coach',
    'schedule' => 'Monday, Thursday, & Saturday',
  ],
  'simic' => [
    'nickname' => 'simic',
    'pass' => 'a',
    'name' => 'Michael Sajadi Putra',
    'birtdate' => '19 April 1987',
    'email' => 'michael.soj87@gmail.com',
    'phone' => '6287885207599',
    'address' => 'Kapuk, Cengkareng, Jakarta Barat',
    'joindate' => 'August 2024',
    'position' => 'U8 & U14 Coach',
    'schedule' => 'Monday',
  ],
  'haikal' => [
    'nickname' => 'haikal',
    'pass' => 'a',
    'name' => 'Muhammad Haikal Fabian',
    'birtdate' => '29 June 2004',
    'email' => 'haikalfabian407@gmail.com',
    'phone' => '6281380906463',
    'address' => 'Pesona Cilebut 2, Blok EB 2, No 6',
    'joindate' => 'June 2024',
    'position' => 'U10',
    'schedule' => 'Tuesday, Wednesday, Thursday, Saturday, Sunday',
  ],
  'savvy' => [
    'nickname' => 'savvy',
    'pass' => 'a',
    'name' => 'Sarvesh Javeri',
    'birtdate' => '11 August 1995',
    'email' => 'javerysarvesh@gmail.com',
    'phone' => '6285715322856',
    'address' => 'Taman Kemayoran Eboni',
    'joindate' => 'December 2022',
    'position' => 'U14',
    'schedule' => 'Thursday & Saturday',
  ],
  'machmud' => [
    'nickname' => 'machmud',
    'pass' => 'a',
    'name' => 'Machmud Faoji',
    'birtdate' => '05 February 1978',
    'email' => 'mahmud.ale11@gmail.com',
    'phone' => '628159553084',
    'address' => 'Perumahan Mega Regency Blok H 44/42, RT 08/09, Jln.Beringin xxx, Suka sari, Kec.Serang Baru, Kab.Bekasi Jawa Barat',
    'joindate' => '2022',
    'position' => 'U12, U16, & U 18',
    'schedule' => 'Saturday',
  ],
  'danen' => [
    'nickname' => 'danen',
    'pass' => 'a',
    'name' => 'Mohammad Danendra Cleosa Susilo',
    'birtdate' => '03 september 2002',
    'email' => 'danendracleosa@gmail.com',
    'phone' => '6281543469706',
    'address' => 'Jl. Pondok Jengkol No.33, Desa Medang Pagedangan, RT/RW 02/05',
    'joindate' => 'November 2025',
    'position' => 'U12, U14, & U18',
    'schedule' => 'TBA From Management',
  ],
  'mika' => [
    'nickname' => 'mika',
    'pass' => 'a',
    'name' => 'Mikail Mantika Pravda',
    'birtdate' => '29 July 2003',
    'email' => 'mikailmantika29@gmail.com',
    'phone' => '6285781704331',
    'address' => 'Jl Tugu Karya 1 no.45 RT002 RW012 Cipondoh, Tangerang, Banten',
    'joindate' => 'November 2023',
    'position' => 'U14',
    'schedule' => 'Thursday & Saturday',
  ],
  'septian' => [
    'nickname' => 'septian',
    'pass' => 'a',
    'name' => 'Mikail Mantika Pravda',
    'birtdate' => '29 September 1991',
    'email' => 'septian.gestiardi@gmail.com',
    'phone' => '628999928852',
    'address' => 'Jl Dipati Ukur no 8, RT 11 RW 04, Uwung Jaya, Cibodas, Tangerang',
    'joindate' => 'October 2025',
    'position' => 'U6 & U16',
    'schedule' => 'Saturday',
  ],
  'mike' => [
    'nickname' => 'mike',
    'pass' => 'a',
    'name' => 'Michael Arif Rahman Kammerlohr',
    'birtdate' => '02 July 2001',
    'email' => 'kammerlohrm@gmail.com',
    'phone' => '6282146391424',
    'address' => 'De Latinos Cluster Brazilia Flamengo D16/1, Serpong, Tangerang Selatan, 15314',
    'joindate' => 'October 2023',
    'position' => 'U10',
    'schedule' => 'Monday, Thursday, & Saturday',
  ],
  'alfons' => [
    'nickname' => 'alfons',
    'pass' => 'a',
    'name' => 'Alfonsius Kelvan',
    'birtdate' => '21 June 1989',
    'email' => '-',
    'phone' => '6287821898888',
    'address' => 'Jl. Batu Merah No.6 5, RT.5/RW.2, Pejaten Timur, Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12510',
    'joindate' => 'October 2025',
    'position' => 'U14 & U16',
    'schedule' => 'Thursday & Saturday',
  ],
  'reyhan' => [
    'nickname' => 'reyhan',
    'pass' => 'a',
    'name' => 'Reyhan Amalatu Muskita',
    'birtdate' => '20 November 2001',
    'email' => 'reyhanmuskita20@gmail.com',
    'phone' => '6281296316655',
    'address' => 'Jl. Lili Blok G3/1',
    'joindate' => 'October 2023',
    'position' => 'U6 & U18',
    'schedule' => 'Monday, Thursday, & Saturday',
  ],
  'fabrice' => [
    'nickname' => 'fabrice',
    'pass' => 'a',
    'name' => 'Fabrice Constantine Permana',
    'birtdate' => '13 September 2005',
    'email' => 'fabriceperm4na@gmail.com',
    'phone' => '628176722190',
    'address' => 'BSD Nusaloka, Jl Samosir 1 Blok H1 No 15',
    'joindate' => 'March 2025',
    'position' => 'U8 & U12',
    'schedule' => 'Wednesday & Saturday',
  ],
  'nic' => [
    'nickname' => 'nic',
    'pass' => 'a',
    'name' => 'Nicholas Simon',
    'birtdate' => '07 December 1996',
    'email' => 'ns.robson07@gmail.com',
    'phone' => '62895606925892',
    'address' => 'Cluster Chalcedony Barat 7 no 48',
    'joindate' => 'November 2025',
    'position' => 'U10 & U12',
    'schedule' => 'Saturday',
  ],
  'ali' => [
    'nickname' => 'ali',
    'pass' => 'a',
    'name' => 'Ali Ali',
    'birtdate' => '18 September 1995',
    'email' => 'coachalikribo@gmail.con',
    'phone' => '6287877173500',
    'address' => '-',
    'joindate' => 'May 2024',
    'position' => 'U16',
    'schedule' => 'Saturday',
  ],
];
?>