<?php
$users = [
  'damai' => [
    'nickname' => 'damai',
    'pass' => 'a',
    'name' => 'Damai Miracle Tampubolon',
    'birtdate' => '21 February 1997',
    'email' => 'damaimiracle@gmail.com',
    'phone' => '6281336698883',
    'address' => 'Jalan Minas 7, Blok G7 no. 27, Jatiwaringin, Bekasi',
    'joindate' => 'September 2024',
    'position' => 'Head Coach',
    'schedule' => 'Monday & Saturday',
  ],
  'kenda' => [
    'nickname' => 'kenda',
    'pass' => 'a',
    'name' => 'M Keinanda Alam',
    'birtdate' => '13 September 1999',
    'email' => 'akeinanda@gmail.com',
    'phone' => '6285776675400',
    'address' => 'Apartemen Menara Kebon Jeruk. Jl.Arjuna Utara - Jakarta Barat',
    'joindate' => 'September 2024',
    'position' => 'U10 Coach',
    'schedule' => 'Saturday',
  ],
  'rafly' => [
    'nickname' => 'rafly',
    'pass' => 'a',
    'name' => 'Muhammad Rafly Alfariz',
    'birtdate' => '03 September 2002',
    'email' => 'raflyalfariz@gmail.com',
    'phone' => '6282120242003',
    'address' => 'Taman Adhiloka Blok K 16, Tangerang, Banten',
    'joindate' => 'August 2025',
    'position' => 'U12 Borussia Coach',
    'schedule' => 'Monday, Thursday, & Saturday',
  ],
  'simic' => [
    'nickname' => 'simic',
    'pass' => 'a',
    'name' => 'Michael Sajadi Putra',
    'birtdate' => '19 April 1987',
    'email' => 'michael.soj87@gmail.com',
    'phone' => '6287885207599',
    'address' => 'Kapuk, Cengkareng, Jakarta Barat',
    'joindate' => 'August 2024',
    'position' => 'U8 & U14 Coach',
    'schedule' => 'Monday',
  ],
  'haikal' => [
    'nickname' => 'haikal',
    'pass' => 'a',
    'name' => 'Muhammad Haikal Fabian',
    'birtdate' => '29 June 2004',
    'email' => 'haikalfabian407@gmail.com',
    'phone' => '081380906463',
    'address' => 'Pesona Cilebut 2, Blok EB 2, No 6',
    'joindate' => 'June 2024',
    'position' => 'U10',
    'schedule' => 'Tuesday, Wednesday, Thursday, Saturday, Sunday',
  ],
];
?>